version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/Flask_db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: Flask_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
